### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by RaymiiOrg** [ThreeFx/3fx-blog#2]
Does your blog have an rss feed?

**Comment by ThreeFx** [comment]
I'm currently working on a redesign which will come with an RSS/Atom feed (haven't decided yet). If you have any suggestions which go well with Hugo I'll gladly check them out!

**Comment by RaymiiOrg** [comment]
Sorry I'm no expert on Hugo, I've written my own static site generator...

**Comment by ThreeFx** [comment]
Ah, I remember seeing that when I clicked around on your blog, that's pretty cool :)

Anyway there's an RSS feed now available [here](https://3fx.ch/blog/index.xml) (although I do have to write some posts for that to make sense at all...) Have fun!
